const AUTH0_DOMAIN_NAME = process.env.REACT_APP_AUTH0_DOMAIN_NAME;
const AUTH0_CLIENT_ID = process.env.REACT_APP_AUTH0_CLIENT_ID;
const AUTH0_AUDIENCE = process.env.REACT_APP_AUTH0_AUDIENCE;
const AUTH0_SCOPE = process.env.REACT_APP_AUTH0_SCOPE;

const AUTH0_DATABASE_CONNECTION = process.env.REACT_APP_AUTH0_DATABASE_CONNECTION;

module.exports = {
  AUTH0_DOMAIN_NAME,
  AUTH0_CLIENT_ID,
  AUTH0_AUDIENCE,
  AUTH0_SCOPE,
  AUTH0_DATABASE_CONNECTION
};